#!/usr/bin/env python3
"""A WPA2-PSK 4-way handshake and a group rekey, as an AP would run them,
computed independently of src/rgb30/wpa.c (hashlib, hmac and the
`cryptography` package's AES key wrap). Writes tests/rgb30/wpa_vectors.h,
which tests/rgb30/wpa_test.c checks wpa.c against:

    python3 tests/rgb30/wpa_vectors.py > tests/rgb30/wpa_vectors.h
"""
import hashlib
import hmac
import struct

from cryptography.hazmat.primitives.keywrap import aes_key_wrap

PASS = b"bm-console-2026"
SSID = b"CasaRossi"
AA = bytes.fromhex("021122334455")          # the AP
SPA = bytes.fromhex("00e04c8821c0")         # the RGB30
ANONCE = bytes(range(0x10, 0x30))
SNONCE = bytes(range(0xa0, 0xc0))
GTK = bytes.fromhex("8f7e6d5c4b3a29180716253443526170")
GTK2 = bytes.fromhex("00112233445566778899aabbccddeeff")
# our RSN IE: PSK, CCMP pairwise and group, no capabilities
RSN_IE = bytes.fromhex("30140100000fac040100000fac040100000fac020000")


def prf(key, label, data, n):
    out = b""
    i = 0
    while len(out) < n:
        out += hmac.new(key, label + b"\0" + data + bytes([i]), hashlib.sha1).digest()
        i += 1
    return out[:n]


def eapol_key(info, key_len, replay, nonce=bytes(32), data=b"", version=2, kck=None):
    body = struct.pack(">BHH", 2, info, key_len) + struct.pack(">Q", replay) + nonce
    body += bytes(16) + bytes(8) + bytes(8) + bytes(16) + struct.pack(">H", len(data)) + data
    frame = struct.pack(">BBH", version, 3, len(body)) + body
    if kck:
        mic = hmac.new(kck, frame, hashlib.sha1).digest()[:16]
        frame = frame[:81] + mic + frame[97:]
    return frame


def gtk_kde(gtk, keyid):
    """key data: the AP's RSN IE, the GTK KDE, padding DD 00.. to 8 bytes"""
    kde = bytes([0xdd, 6 + len(gtk), 0x00, 0x0f, 0xac, 0x01, keyid, 0]) + gtk
    ap_ie = RSN_IE[:-2] + b"\x0c\x00"           # the AP's capabilities differ from ours
    data = ap_ie + kde
    pad = (8 - len(data) % 8) % 8
    if pad:
        data += b"\xdd" + bytes(pad - 1)
    return data


pmk = hashlib.pbkdf2_hmac("sha1", PASS, SSID, 4096, 32)
lo = min(AA, SPA) + max(AA, SPA) + min(ANONCE, SNONCE) + max(ANONCE, SNONCE)
ptk = prf(pmk, b"Pairwise key expansion", lo, 48)
kck, kek, tk = ptk[:16], ptk[16:32], ptk[32:]

m1 = eapol_key(0x008a, 16, 1, ANONCE)
m2 = eapol_key(0x010a, 0, 1, SNONCE, RSN_IE, kck=kck)
m3_data = aes_key_wrap(kek, gtk_kde(GTK, 1))
m3 = eapol_key(0x13ca, 16, 2, ANONCE, m3_data, kck=kck)
m4 = eapol_key(0x030a, 0, 2, kck=kck)
g1_data = aes_key_wrap(kek, gtk_kde(GTK2, 2))
g1 = eapol_key(0x1382, 16, 3, bytes(32), g1_data, kck=kck)
g2 = eapol_key(0x0302, 0, 3, kck=kck)
m3_bad = m3[:90] + bytes([m3[90] ^ 1]) + m3[91:]    # a wrong MIC (another password)


def c_array(name, data):
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


print("/* generated by tests/rgb30/wpa_vectors.py: do not edit */")
print(f'#define V_PASS "{PASS.decode()}"')
print(f'#define V_SSID "{SSID.decode()}"')
for name, data in [("v_aa", AA), ("v_spa", SPA), ("v_snonce", SNONCE), ("v_rsn_ie", RSN_IE),
                   ("v_pmk", pmk), ("v_ptk", ptk), ("v_gtk", GTK), ("v_gtk2", GTK2),
                   ("v_m1", m1), ("v_m2", m2), ("v_m3", m3), ("v_m4", m4), ("v_g1", g1),
                   ("v_g2", g2), ("v_m3_bad", m3_bad)]:
    print(c_array(name, data))
