-- Worlds and stages. A layout is a list of rows, the first one at the back
-- of the kitchen (top of the screen). Characters: see 12_stations.lua.
-- Stage fields:
--   time      seconds of service
--   recipes   the dishes that can be ordered
--   wash      served plates come back dirty (to R) and must be washed (S)
--   plates    clean plates at the start
--   plats     moving platforms { x, y, w, h (layout cells), dx, dy, period }
--   haz       hazards { kind = "vent"/"door"/"shelf"/"cart"/"leak"..., ... }
--   dis       disasters { kind, at (seconds), every (seconds, repeats) }
--   tip       one line shown before the stage

Data.WORLDS = {
  { name = "LITTLE DINER", tag = "Where it all begins",
    floor1 = 0xEADCC0, floor2 = 0xD6C29E, wall = 0xD86A50, wall2 = 0xF0E6D0, sky = 0x6AB8D8,
    base = 0x8A5A38, mech = "chop, cook, plate, serve", music = 1 },
  { name = "MARKET DISTRICT", tag = "Busy stalls, rolling carts",
    floor1 = 0xD8D0C8, floor2 = 0xB8ACA0, wall = 0x3E8A5A, wall2 = 0xE8E0C8, sky = 0x88C0E8,
    base = 0x6A5A4A, mech = "conveyor belts, market carts, rats", music = 2 },
  { name = "HARBOR", tag = "Kitchens afloat",
    floor1 = 0xC89A6A, floor2 = 0xAE8250, wall = 0x3A6AA0, wall2 = 0xE8F0F8, sky = 0x5AA8E0,
    base = 0x2A5A8A, water = 0x2E7AC0, mech = "moving decks, ducks", music = 3 },
  { name = "MOUNTAIN RESORT", tag = "Mind the ice",
    floor1 = 0xE8F0F8, floor2 = 0xC8D8E8, wall = 0x8A5A3A, wall2 = 0xF8F8F8, sky = 0x9AC8F0,
    base = 0x6A7A8A, water = 0xA8D8F0, mech = "ice, leaks, steam vents", music = 4 },
  { name = "OLD CASTLE", tag = "Something moves in the dark",
    floor1 = 0x8A8478, floor2 = 0x70695E, wall = 0x5A4E6A, wall2 = 0xB0A490, sky = 0x2A2440,
    base = 0x3A3446, water = 0x302850, mech = "doors, ghosts, haunted pans", music = 5 },
  { name = "CHAOS DISTRICT", tag = "Everything, all at once",
    floor1 = 0xE8C8E8, floor2 = 0xC8A0D0, wall = 0xE04890, wall2 = 0xF8E8A0, sky = 0x402060,
    base = 0x502860, water = 0x6040C0, mech = "all of it, and a tornado", music = 6 },
}

Data.STAGES = {
  ------------------------------------------------------------ world 1
  { id = "1-1", world = 1, name = "Opening Day", time = 150, plates = 4,
    recipes = { "tomato_soup" },
    tip = "Chop tomatoes (X), 3 in a pot, then plate the soup and serve it!",
    layout = {
      "##############",
      "#CCtCBCBCPCPC#",
      "#............#",
      "#.1..........W",
      "#.....CC...2.#",
      "#.3........4.#",
      "#............#",
      "CCCTCCDCCCCCCC",
    } },
  { id = "1-2", world = 1, name = "Soup of the Day", time = 180, plates = 4,
    recipes = { "tomato_soup", "onion_soup" },
    tip = "Two soups now. Keep an eye on the pots: they burn!",
    layout = {
      "##############",
      "#CtCoCBCB#PCP#",
      "#........#...#",
      "#.1...2..#...W",
      "#............#",
      "#...3...4....#",
      "#........#...#",
      "CCDCCTCCC#CCCC",
    } },
  { id = "1-3", world = 1, name = "Suds and Salads", time = 180, plates = 3, wash = true,
    recipes = { "green_salad", "sunny_salad", "tomato_soup" },
    tip = "Plates come back dirty: wash them in the sink (X).",
    layout = {
      "##############",
      "#CClCuCtCBCBC#",
      "#............#",
      "#.1.CCCPCP.2.W",
      "#............#",
      "#.3........4.#",
      "#............#",
      "CRSCCDCCCTCCCC",
    } },
  { id = "1-4", world = 1, name = "Sizzle School", time = 180, plates = 4, wash = true,
    recipes = { "scrambled", "sizzle_dog", "butter_pasta" },
    tip = "Pans fry one thing at a time. Take it off before it burns!",
    layout = {
      "##############",
      "#CeCgCnCbCyCa#",
      "#............#",
      "#.1..CBCB..2.W",
      "#............#",
      "#.3..FCFCP.4.#",
      "#............#",
      "CCRSCCCDCCTCCC",
    } },
  { id = "1-5", world = 1, name = "Over the Counter", time = 200, plates = 4, wash = true,
    recipes = { "tomato_soup", "sunny_salad", "sizzle_dog" },
    tip = "The counter splits the kitchen: throw (Y) or pass things across!",
    layout = {
      "##############",
      "#CtClCgCb#PCF#",
      "#......C.....#",
      "#.1....C...2.W",
      "#............#",
      "#.3....C...4.#",
      "#......C.....#",
      "CBCBRSCCCCDCTC",
    } },

  ------------------------------------------------------------ world 2
  { id = "2-1", world = 2, name = "Market Morning", time = 200, plates = 4, wash = true,
    recipes = { "cheese_toast", "mush_toast", "baked_potato" },
    tip = "The oven bakes up to four things together. Don't let it burn!",
    layout = {
      "################",
      "#CbChCmCpCyCBCB#",
      "#..............#",
      "#.1..........2.W",
      "#....CCOCOCC...#",
      "#.3..........4.#",
      "#..............#",
      "CRSCCDCCTCCCECCC",
    } },
  { id = "2-2", world = 2, name = "Conveyor Lane", time = 210, plates = 4, wash = true,
    recipes = { "garden_soup", "cheese_toast", "stuffed_pot" },
    tip = "Put things on the belt: it carries them across the kitchen.",
    layout = {
      "################",
      "#CpCcCoCh#CBCBC#",
      "#.........T....#",
      "#.1..>>>>>C..2.W",
      "#..C.......PCP.#",
      "#..b...........#",
      "#.3.C.....O.4..#",
      "CmCCCRSCDCCCOCCC",
    } },
  { id = "2-3", world = 2, name = "Cart Crossing", time = 210, plates = 4, wash = true,
    recipes = { "cheeseburger", "crispy_burger", "chick_sand" },
    tip = "Market carts roll through. Wait for them, or go round!",
    haz = { { kind = "cart", row = 4, speed = 1.5 } },
    layout = {
      "################",
      "#CbCsChCiCtClCC#",
      "#..............#",
      "#.1..BCBCB...2.W",
      "#..............#",
      "#.3..FCFCF...4.#",
      "#..............#",
      "CRSCCDCCCTCCECCC",
    } },
  { id = "2-4", world = 2, name = "Rat Race", time = 220, plates = 4, wash = true,
    recipes = { "garden_pizza", "mush_pizza", "sunny_pizza" },
    tip = "Rats steal food and hide in crates: chase them off (A or dash)!",
    dis = { { kind = "rats", at = 25, every = 40 } },
    layout = {
      "################",
      "#CfChCtCoCmCnCC#",
      "#..............#",
      "#.1..CBCBCB..2.W",
      "#..............#",
      "#.3..COCOCO..4.#",
      "#..............#",
      "CRSCCDCCCTCCECCC",
    } },
  { id = "2-5", world = 2, name = "Grand Bazaar", time = 230, plates = 5, wash = true,
    recipes = { "red_pasta", "mush_pasta", "chick_sand", "cheeseburger" },
    tip = "Belts, carts and rats: split the jobs between you!",
    haz = { { kind = "cart", row = 5, speed = 1.3 } },
    dis = { { kind = "rats", at = 40, every = 50 } },
    layout = {
      "################",
      "#CaCtChCmCbCiCl#",
      "#..............#",
      "#.1.>>>>>>>C.2.W",
      "#..............#",
      "#.3..........4.#",
      "#..BC.BPC.PF.Fs#",
      "CRSCCDCCCTCCECCC",
    } },
  ------------------------------------------------------------ world 3
  { id = "3-1", world = 3, name = "Pier Pressure", time = 210, plates = 4, wash = true,
    recipes = { "fish_bun", "harbor_roll", "herb_rice" },
    tip = "One narrow bridge. Throwing across the water is faster!",
    layout = {
      "################",
      "#CbCxClCu#CrCnC#",
      "#........__....#",
      "#.1......__..2.W",
      "#..BCB.........#",
      "#.3.FCF..__.4..#",
      "#........__PCP.#",
      "CRSCDCCCC__CCCTC",
    } },
  { id = "3-2", world = 3, name = "Ferry Kitchen", time = 220, plates = 4, wash = true,
    recipes = { "shrimp_rice", "fried_rice", "herb_rice" },
    tip = "The ferry goes back and forth. Hop on, and mind the gap!",
    plats = { { x = 8, y = 3, w = 2, h = 2, dx = 1, period = 8 } },
    layout = {
      "################",
      "#CrCeCcC___CFCF#",
      "#.......___....#",
      "#.1.....C.._.2.W",
      "#........._....#",
      "#.3.....___..4.#",
      "#.BCB...___.PCP#",
      "CRSCzCnC___DCCTE",
    } },
  { id = "3-3", world = 3, name = "Rocking Boats", time = 230, plates = 4, wash = true,
    recipes = { "tomato_soup", "onion_soup", "fish_bun", "sunny_salad" },
    tip = "The stoves are on two boats. Use each one while it is docked.",
    plats = { { x = 2, y = 2, w = 4, h = 2, dy = 1, period = 12, phase = 6 },
              { x = 9, y = 2, w = 4, h = 2, dy = 1, period = 12, phase = 0 } },
    layout = {
      "################",
      "#______________#",
      "#_CPCB___CFCB__#",
      "#_....___....__#",
      "#______________#",
      "#.1..........2.W",
      "#.3..........4.#",
      "CtClCxCoCbCDCRSE",
    } },
  { id = "3-4", world = 3, name = "Duck Season", time = 220, plates = 4, wash = true,
    recipes = { "harbor_roll", "shrimp_rice", "herb_rice", "fish_bun" },
    tip = "Ducks waddle in and eat chopped food. Shoo them with a dash!",
    dis = { { kind = "ducks", at = 30, every = 55 } },
    layout = {
      "################",
      "#CrCuCxCnCbClCz#",
      "#..............#",
      "#.1..BCB..PCP2.W",
      "#..............#",
      "#.3..FCF..PCP4.#",
      "#..............#",
      "CRSCCDCCTCCCECCC",
    } },
  { id = "3-5", world = 3, name = "Stormy Galley", time = 240, plates = 5, wash = true,
    recipes = { "veg_curry", "chick_curry", "shrimp_curry" },
    tip = "Two pots per curry: rice in one, the rest in the other.",
    plats = { { x = 4, y = 3, w = 4, h = 2, dx = 2, period = 10 } },
    dis = { { kind = "ducks", at = 50, every = 60 } },
    layout = {
      "################",
      "#CrCcCoCpCiCzCt#",
      "#..............#",
      "#.1.CPCP__...2.W",
      "#...B..B__.....#",
      "#.3..........4.#",
      "#.BCB....PCPCF.#",
      "CRSCCDCCTCCCECCC",
    } },
  ------------------------------------------------------------ world 4
  { id = "4-1", world = 4, name = "Slippery Slopes", time = 200, plates = 4, wash = true,
    recipes = { "smoothie", "fruit_salad", "choco_shake" },
    tip = "Ice! You slide: let go early to stop where you want.",
    layout = {
      "################",
      "#CqCkCjCBCBCMCM#",
      "#..............#",
      "#.1.~~~~~~~~.2.W",
      "#...~~~~~~~~...#",
      "#.3.~~~~~~~~.4.#",
      "#..............#",
      "CRSCCDCCTCCCECCC",
    } },
  { id = "4-2", world = 4, name = "Steam Room", time = 220, plates = 4, wash = true,
    recipes = { "fondue", "hot_cocoa", "smoothie" },
    tip = "Vents hiss before they blow. Step off when you hear them!",
    layout = {
      "################",
      "#ChCkCjCqCbCBCB#",
      "#..............#",
      "#.1..^....^..2.W",
      "#...CPCPCMCM...#",
      "#.3..^....^..4.#",
      "#..............#",
      "CRSCCDCCTCCCECCC",
    } },
  { id = "4-3", world = 4, name = "Frozen Pipes", time = 220, plates = 4, wash = true,
    recipes = { "pancakes", "omelette", "smoothie" },
    tip = "A pipe will burst: find the red valve and hold X to fix it.",
    dis = { { kind = "leak", at = 35, every = 60 } },
    layout = {
      "################",
      "#CeCfCkCqChCBCB#",
      "#..............#",
      "#.1..MCM..FCF2.W",
      "#...~~~~~~.....#",
      "#.3.~~~~~~...4.#",
      "#..............#",
      "CRSCCDCCTCCCECCC",
    } },
  { id = "4-4", world = 4, name = "Avalanche Alley", time = 230, plates = 4, wash = true,
    recipes = { "fondue", "pancakes", "hot_cocoa" },
    tip = "Snow boxes fall from the shelves. Watch for the shadows!",
    haz = { { kind = "shelf", every = 13, first = 12, stay = 9 } },
    layout = {
      "################",
      "#ChCkCjCqCeCfCb#",
      "#..............#",
      "#.1.~~~~~~~~.2.W",
      "#.PCPBCB.MCMFCF#",
      "#.3.~~~~~~~~.4.#",
      "#..............#",
      "CRSCCDCCTCCCECCC",
    } },
  { id = "4-5", world = 4, name = "Summit Service", time = 240, plates = 5, wash = true,
    recipes = { "smoothie", "fondue", "pancakes", "omelette", "choco_shake" },
    tip = "Ice, steam and a leaky pipe. Stay calm and keep cooking!",
    dis = { { kind = "leak", at = 60, every = 70 } },
    layout = {
      "################",
      "#CkChCjCqCeCfCb#",
      "#..............#",
      "#.1.^~~~~~~^.2.W",
      "#..MCM.PCP.FCF.#",
      "#.3.^~~~~~~^.4.#",
      "#........BCB...#",
      "CRSCCDCCTCCCECCC",
    } },
  ------------------------------------------------------------ world 5
  { id = "5-1", world = 5, name = "Castle Gates", time = 230, plates = 4, wash = true,
    recipes = { "deluxe_pizza", "grill_plate" },
    tip = "The gates open and close. The lock blinks before they shut!",
    layout = {
      "################",
      "#ChCfCgCtCmCsCi#",
      "#..B.B.#.......#",
      "#.1....+.....2.W",
      "#.OCO..#.FCFCF.#",
      "#.3....+.....4.#",
      "#......#.......#",
      "CRSCCDCCCCCCECTC",
    } },
  { id = "5-2", world = 5, name = "Haunted Pantry", time = 230, plates = 4, wash = true,
    recipes = { "castle_stew", "grill_plate", "mush_soup" },
    tip = "Ghosts turn the lights off and spill the crates. Keep calm!",
    dis = { { kind = "ghosts", at = 25, every = 45 } },
    layout = {
      "################",
      "#CsCcCpCbCnCiCg#",
      "#..............#",
      "#.1..BCBCB...2.W",
      "#..............#",
      "#.3..PCPCFCF.4.#",
      "#..............#",
      "CRSCCDCmCoCTCECC",
    } },
  { id = "5-3", world = 5, name = "Possessed Pans", time = 240, plates = 4, wash = true,
    recipes = { "rice_bowl", "choco_cake", "deluxe_pizza" },
    tip = "Haunted pans and knives come alive: grab them (A) to calm them.",
    dis = { { kind = "possessed", at = 25, every = 35 } },
    layout = {
      "################",
      "#CrCsCeCcCjCfCq#",
      "#..............#",
      "#.1.BCBCB.MCM2.W",
      "#..............#",
      "#.3.PCFCFCF.O4.#",
      "#.........O....#",
      "CRSCCDChCtCgTmEC",
    } },
  { id = "5-4", world = 5, name = "The Poltergeist", time = 240, plates = 4, wash = true,
    recipes = { "fruit_tart", "grill_plate", "castle_stew" },
    tip = "Something moves your food around. Look before you grab!",
    dis = { { kind = "poltergeist", at = 30, every = 30 } },
    layout = {
      "################",
      "#CyCeCfCqCsCiCg#",
      "#..B.B...#.P...#",
      "#.1......+...2.W",
      "#.MCO....#.FCF.#",
      "#.3......+...4.#",
      "#........#.....#",
      "CRSCDCcCpCbCnETC",
    } },
  { id = "5-5", world = 5, name = "Midnight Banquet", time = 250, plates = 5, wash = true,
    recipes = { "deluxe_pizza", "rice_bowl", "choco_cake", "scrambled" },
    tip = "Ghosts, gates and haunted pans. The castle's big night!",
    dis = { { kind = "ghosts", at = 30, every = 60 }, { kind = "possessed", at = 60, every = 50 } },
    layout = {
      "################",
      "#CrCsCeCcCjCfCq#",
      "#..B.B...#.M.O.#",
      "#.1......+...2.W",
      "#.PCF....#.FCO.#",
      "#.3......+...4.#",
      "#........#.....#",
      "CRSCDChCtCgnmETC",
    } },
  ------------------------------------------------------------ world 6
  { id = "6-1", world = 6, name = "Spin Cycle", time = 240, plates = 4, wash = true,
    recipes = { "royal_burger", "tower_burger", "cheeseburger" },
    tip = "The middle of the kitchen turns. Things are never where you left them!",
    plats = { { x = 6, y = 3, w = 3, h = 3, rotate = true, period = 9 } },
    layout = {
      "################",
      "#CbCsChCeClCtCC#",
      "#..............#",
      "#.1...BCF....2.W",
      "#......C.......#",
      "#.3...FCB....4.#",
      "#..............#",
      "CRSCCDCCTCCCECCC",
    } },
  { id = "6-2", world = 6, name = "Runaway Food", time = 240, plates = 4, wash = true,
    recipes = { "paella", "harbor_pasta", "sea_plate" },
    tip = "The ingredients try to escape. Catch them before they roll away!",
    dis = { { kind = "runaway", at = 20, every = 25 } },
    layout = {
      "################",
      "#CrCzCtCxCnCaCl#",
      "#..............#",
      "#.1..BCBCB...2.W",
      "#..............#",
      "#.3..PCPCFCF.4.#",
      "#..............#",
      "CRSCCDCCTCCCECCC",
    } },
  { id = "6-3", world = 6, name = "Twister", time = 250, plates = 4, wash = true,
    recipes = { "carbonara", "lasagna", "red_pasta" },
    tip = "A tiny tornado! It spins you round and scatters loose food.",
    dis = { { kind = "tornado", at = 30, every = 55 } },
    layout = {
      "################",
      "#CaChCeCgCsCtCC#",
      "#..............#",
      "#.1..BCB.MCM.2.W",
      "#..............#",
      "#.3..PCPCFCF.4.#",
      "#.........O....#",
      "CRSCCDCCTCCEOCCC",
    } },
  { id = "6-4", world = 6, name = "Rush Hour", time = 250, plates = 5, wash = true,
    recipes = { "lasagna", "chaos_feast", "tower_burger" },
    tip = "Belts, carts and rats at the busiest hour. Talk to each other!",
    haz = { { kind = "cart", row = 2, speed = 1.7 } },
    dis = { { kind = "rats", at = 30, every = 40 } },
    layout = {
      "################",
      "#CbCsChCfCmCtCi#",
      "#..............#",
      "#.1M.O.O.F.F.2.W",
      "#...BCBCB..P...#",
      "#.3.>>>>>>>>C4.#",
      "#..............#",
      "CRSCCDClCaCqTkEC",
    } },
  { id = "6-5", world = 6, name = "Everything Everywhere", time = 260, plates = 5, wash = true,
    recipes = { "paella", "fruit_tart", "pancakes", "smoothie" },
    tip = "A drifting deck, ducks and ghosts. Almost there!",
    plats = { { x = 4, y = 3, w = 3, h = 2, dx = 3, period = 11 } },
    dis = { { kind = "ducks", at = 30, every = 60 }, { kind = "ghosts", at = 70, every = 60 } },
    layout = {
      "################",
      "#CrCzCtCxCnCeCf#",
      "#..............#",
      "#.1.MCO___...2.W",
      "#...B.B___.....#",
      "#.3..........4.#",
      "#.PCP.FCF.MCO..#",
      "CRSCCDCqCyCkCTCE",
    } },
  { id = "6-6", world = 6, name = "The Final Service", time = 270, plates = 5, wash = true,
    recipes = { "royal_burger", "lasagna", "carbonara" },
    tip = "The last kitchen. Steam, a tornado and runaway food. Good luck, chefs!",
    dis = { { kind = "tornado", at = 45, every = 60 }, { kind = "runaway", at = 25, every = 40 } },
    layout = {
      "################",
      "#CbCsChCeClCtCa#",
      "#..P.P.F.F.F.O.#",
      "#.1..^...^...2.W",
      "#...BCB.MCM....#",
      "#.3.....^....4.#",
      "#..............#",
      "CRSCCDCgCCTCCCEC",
    } },
}

Data.STAGE = {}
for i, s in ipairs(Data.STAGES) do
  s.n = i
  Data.STAGE[s.id] = s
end
