#!/usr/bin/env python3
"""
Converts a PSF1/PSF2 console font (optionally .gz) with a Unicode table into
a C array of 256 8xN glyphs in code page 437 order.

  psf2c.py /usr/share/consolefonts/Uni2-Terminus16.psf.gz > src/gfx/font8x16.c

Glyphs missing from the font are left blank.
"""
import gzip
import struct
import sys


def load_psf(path):
    data = open(path, "rb").read()
    if data[:2] == b"\x1f\x8b":
        data = gzip.decompress(data)

    if data[:4] == b"\x72\xb5\x4a\x86":
        _, _, hdr, flags, count, size, height, width = struct.unpack("<8I", data[:32])
        glyphs = [data[hdr + i * size: hdr + (i + 1) * size] for i in range(count)]
        table = data[hdr + count * size:] if flags & 1 else b""
        umap = {}
        for i, entry in enumerate(table.split(b"\xff")[:count]):
            for seq in entry.split(b"\xfe")[:1]:
                for ch in seq.decode("utf-8", "ignore"):
                    umap.setdefault(ord(ch), i)
        return width, height, glyphs, umap

    if data[:2] == b"\x36\x04":
        mode, size = data[2], data[3]
        count = 512 if mode & 1 else 256
        glyphs = [data[4 + i * size: 4 + (i + 1) * size] for i in range(count)]
        umap = {}
        if mode & 2:
            tab = data[4 + count * size:]
            i = 0
            for pos in range(0, len(tab) - 1, 2):
                (u,) = struct.unpack("<H", tab[pos:pos + 2])
                if u == 0xFFFF:
                    i += 1
                elif u != 0xFFFE:
                    umap.setdefault(u, i)
        return 8, size, glyphs, umap

    raise SystemExit("not a PSF font")


def main():
    width, height, glyphs, umap = load_psf(sys.argv[1])
    if width != 8:
        raise SystemExit("only 8-pixel wide fonts are supported")

    print("/*")
    print(" * bm33 console font 8x%d, derived from Terminus Font (c) Dimitar Toshkov Zhekov," % height)
    print(" * SIL Open Font License 1.1 (see docs/LICENSE.font).")
    print(" * Generated by scripts/psf2c.py - do not edit.")
    print(" * Glyphs are in code page 437 order; one byte per row, MSB = left.")
    print(" */")
    print("#include \"font.h\"\n")
    print(f"static const uint8_t glyphs[256][{height}] = {{")
    missing = []
    for code in range(256):
        ch = bytes([code]).decode("cp437")
        if code == 0:
            idx = None
        else:
            idx = umap.get(ord(ch))
        rows = glyphs[idx] if idx is not None else bytes(height)
        if idx is None and code:
            missing.append(code)
        label = ch if 0x20 <= code < 0x7F and ch not in "\\" else f"0x{code:02x}"
        print("    { " + ", ".join(f"0x{b:02x}" for b in rows) + f" }}, /* {label} */")
    print("};\n")
    print("const font_t font_console_8x%d = {" % height)
    print(f"    .width = 8, .height = {height}, .glyphs = &glyphs[0][0],")
    print("};")
    if missing:
        sys.stderr.write(f"missing glyphs: {missing}\n")


if __name__ == "__main__":
    main()
