/* Generated by tools/qpuasm.py from its SHADERS: do not edit. */
#ifndef GPU_SHADERS_H
#define GPU_SHADERS_H

#include <stdint.h>

static const uint32_t fs_colour[34] __attribute__((aligned(8))) = {
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x153e7d80, 0x100208e7,     /* mov r3, ra15        ; nop */
    0x158e7d80, 0x10020827,     /* mov r0, vary        ; nop */
    0x209e7003, 0x100049e0,     /* fmul r0, r0, r3     ; nop */
    0x818e7176, 0x40024821,     /* fadd r0, r0, r5     ; mov r1, vary  ; sbwait */
    0x209e700b, 0x100049e1,     /* fmul r1, r1, r3     ; nop */
    0x818e7376, 0x10024862,     /* fadd r1, r1, r5     ; mov r2, vary */
    0x209e7013, 0x100049e2,     /* fmul r2, r2, r3     ; nop */
    0x819e7540, 0x114248a3,     /* fadd r2, r2, r5     ; mov r3.8a, r0 */
    0x809e7009, 0x115049e3,     /* nop                 ; mov r3.8b, r1 */
    0x809e7012, 0x116049e3,     /* nop                 ; mov r3.8c, r2 */
    0x809e003f, 0xd17049e3,     /* nop                 ; mov r3.8d, 1.0 */
    0x159cffc0, 0x10020b27,     /* mov tlb_z, rb15     ; nop */
    0x159e76c0, 0x30020ba7,     /* mov tlbc, r3        ; nop           ; thrend */
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x009e7000, 0x500009e7,     /* nop                 ; nop           ; sbdone */
};

static const uint32_t fs_texture[34] __attribute__((aligned(8))) = {
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x153e7d80, 0x100208e7,     /* mov r3, ra15        ; nop */
    0x158e7d80, 0x10020827,     /* mov r0, vary        ; nop */
    0x209e7003, 0x100049e0,     /* fmul r0, r0, r3     ; nop */
    0x019e7140, 0x10020827,     /* fadd r0, r0, r5     ; nop */
    0x158e7d80, 0x10020867,     /* mov r1, vary        ; nop */
    0x209e700b, 0x100049e1,     /* fmul r1, r1, r3     ; nop */
    0x019e7340, 0x10020867,     /* fadd r1, r1, r5     ; nop */
    0x159e7240, 0x10020e67,     /* mov t0t, r1         ; nop */
    0x159e7000, 0x10020e27,     /* mov t0s, r0         ; nop */
    0x009e7000, 0x400009e7,     /* nop                 ; nop           ; sbwait */
    0x159cffc0, 0x10020b27,     /* mov tlb_z, rb15     ; nop */
    0x009e7000, 0xa00009e7,     /* nop                 ; nop           ; ldtmu0 */
    0x159e7900, 0x30020ba7,     /* mov tlbc, r4        ; nop           ; thrend */
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x009e7000, 0x500009e7,     /* nop                 ; nop           ; sbdone */
};

static const uint32_t fs_tex_lit[44] __attribute__((aligned(8))) = {
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x153e7d80, 0x100208e7,     /* mov r3, ra15        ; nop */
    0x158e7d80, 0x10020827,     /* mov r0, vary        ; nop */
    0x209e7003, 0x100049e0,     /* fmul r0, r0, r3     ; nop */
    0x019e7140, 0x10020827,     /* fadd r0, r0, r5     ; nop */
    0x158e7d80, 0x10020867,     /* mov r1, vary        ; nop */
    0x209e700b, 0x100049e1,     /* fmul r1, r1, r3     ; nop */
    0x019e7340, 0x10020867,     /* fadd r1, r1, r5     ; nop */
    0x159e7240, 0x10020e67,     /* mov t0t, r1         ; nop */
    0x159e7000, 0x10020e27,     /* mov t0s, r0         ; nop */
    0x158e7d80, 0x100208a7,     /* mov r2, vary        ; nop */
    0x209e7013, 0x100049e2,     /* fmul r2, r2, r3     ; nop */
    0x019e7540, 0x100208a7,     /* fadd r2, r2, r5     ; nop */
    0x809e7012, 0x113049e1,     /* nop                 ; mov r1.8888, r2 */
    0x009e7000, 0x400009e7,     /* nop                 ; nop           ; sbwait */
    0x159cffc0, 0x10020b27,     /* mov tlb_z, rb15     ; nop */
    0x009e7000, 0xa00009e7,     /* nop                 ; nop           ; ldtmu0 */
    0x609e7021, 0x100049e0,     /* v8muld r0, r4, r1   ; nop */
    0x159e7000, 0x30020ba7,     /* mov tlbc, r0        ; nop           ; thrend */
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x009e7000, 0x500009e7,     /* nop                 ; nop           ; sbdone */
};

static const uint32_t fs_tex_lit_alpha[46] __attribute__((aligned(8))) = {
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x153e7d80, 0x100208e7,     /* mov r3, ra15        ; nop */
    0x158e7d80, 0x10020827,     /* mov r0, vary        ; nop */
    0x209e7003, 0x100049e0,     /* fmul r0, r0, r3     ; nop */
    0x019e7140, 0x10020827,     /* fadd r0, r0, r5     ; nop */
    0x158e7d80, 0x10020867,     /* mov r1, vary        ; nop */
    0x209e700b, 0x100049e1,     /* fmul r1, r1, r3     ; nop */
    0x019e7340, 0x10020867,     /* fadd r1, r1, r5     ; nop */
    0x159e7240, 0x10020e67,     /* mov t0t, r1         ; nop */
    0x159e7000, 0x10020e27,     /* mov t0s, r0         ; nop */
    0x158e7d80, 0x100208a7,     /* mov r2, vary        ; nop */
    0x209e7013, 0x100049e2,     /* fmul r2, r2, r3     ; nop */
    0x019e7540, 0x100208a7,     /* fadd r2, r2, r5     ; nop */
    0x809e7012, 0x113049e1,     /* nop                 ; mov r1.8888, r2 */
    0x009e7000, 0x400009e7,     /* nop                 ; nop           ; sbwait */
    0x009e7000, 0xa00009e7,     /* nop                 ; nop           ; ldtmu0 */
    0x6e9cf9e1, 0xd00248a0,     /* shr r2, r4, 15      ; v8muld r0, r4, r1 */
    0x0e9c95c0, 0xd00229e7,     /* shr.setf nop, r2, 9 ; nop */
    0x159cffc0, 0x10060b27,     /* mov.ifnz tlb_z, rb15 ; nop */
    0x159e7000, 0x30060ba7,     /* mov.ifnz tlbc, r0   ; nop           ; thrend */
    0x009e7000, 0x100009e7,     /* nop                 ; nop */
    0x009e7000, 0x500009e7,     /* nop                 ; nop           ; sbdone */
};

#endif
